Too many agents in the meta graph
LABSS/PyPROTON-OC pull request #33
Opened 2021-08-03 08:46 UTC by Kubasinska

This PR close #24 
**What has been changed?**
Now the meta-graph examines the right number of agents. This greatly increases the runtime speed.

2021-08-03 15:35 UTC, mariopaolucci requested changes
The issue #24 gives no hint of why there were "Too many agents,"  it just gives it as a fact. Two more lines of explanations would have been better.

2021-08-03 15:35 UTC, mariopaolucci commented on protonoc/simulator/model.py
> +            for in_radius_agent in [i for i in agent.agents_in_radius(1) if
Why not
```
for in_radius_agent in in_radius_agent in [i for i in agent.agents_in_radius(1) if != agent]:
```

Is there someone in radius who isn't an agent?

2021-08-04 07:48 UTC, Kubasinska commented on protonoc/simulator/model.py
> +            for in_radius_agent in [i for i in agent.agents_in_radius(1) if
Yes, this is exactly the problem. My mistake for not discussing the issue! Agents entering inside update_meta_links can be of radius greater than 1 because they depend on oc_embeddedness_radius.

2021-08-04 08:18 UTC, Kubasinska commented on protonoc/simulator/model.py
> +            for in_radius_agent in [i for i in agent.agents_in_radius(1) if
More infromation on issue #24

2021-08-04 12:57 UTC, mariopaolucci commented on protonoc/simulator/model.py
> +            for in_radius_agent in [i for i in agent.agents_in_radius(1) if
Ok, I was confused by the use of 'agents' as a variable that for me was `schedule.agents`

Why are we using `agents_in_radius(1)` when there's also `agents_in_radius`? Either we remove the implicit version or we use it.

2021-08-05 07:21 UTC, Kubasinska commented on protonoc/simulator/model.py
> +            for in_radius_agent in [i for i in agent.agents_in_radius(1) if
`_agents_in_radius` is a ghost function that serve to `agents_in_radius`. In my opinion, It is better to use `agents_in_radius(1)` instead of `_agents_in_radius` for consistency with the other calls with different radius.
 For this reason, `_agents_in_radius` starts with an underscore, a convention that the function is a ghost function.

2021-08-05 13:21 UTC, mariopaolucci commented on protonoc/simulator/model.py
> +            for in_radius_agent in [i for i in agent.agents_in_radius(1) if
You're right, I'm convinced. Nest one!

2021-08-05 15:59 UTC, merged